### ISSUE TITLE
compile error with gcc 7.1.0

### ISSUE THREAD

**Issue by handrake0724** [schulzchristian/KaHIP#13]
the latest git version makes compile error with gcc 7.1.0 as follows:

gcc/7.1.0/include/c++/7.1.0/utility:147:12: error: partial specialization of 'struct std::__is_tuple_like_impl<std::pair<_T1, _T2> >' after instantiation of 'struct std::__is_tuple_like_impl<std::pair<unsigned int, unsigned int> >' [-fpermissive]
     struct __is_tuple_like_impl<std::pair<_T1, _T2>> : true_type
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cpptoo: partition_snapshooter.cpp
    cpptoo: graph_partitioner.cpp
    cpptoo: wcycle_partitioner.cpp

Any idea?

**Comment by schulzchristian** [comment]
I will issue a fix soon, can you in the meanwhile use an older version of gcc?

Best
Christian

**Comment by schulzchristian** [comment]
Hi,

I just tried to reproduce the error, however, everything works fine with gcc-7.1.0 on my machine. Can you try the latest state of the git hub repository and tell me if you still get the error? 

Thanks
Christian

**Comment by handrake0724** [comment]
I pulled the repository and tried again to get the following error:
```
In file included from /opt/HPC/Compilers/gcc/7.1.0/include/c++/7.1.0/algorithm:60:0,
                 from interface/../lib/partition/uncoarsening/separator/area_bfs.h:8,
                 from interface/kaHIP_interface.cpp:32:
/opt/HPC/Compilers/gcc/7.1.0/include/c++/7.1.0/utility:147:12: error: partial specialization of 'struct std::__is_tuple_like_impl<std::pair<_T1, _T2> >' after instantiation of 'struct std::__is_tuple_like_impl<std::pair<unsigned int, unsigned int> >' [-fpermissive]
     struct __is_tuple_like_impl<std::pair<_T1, _T2>> : true_type
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cpptoo: size_constraint_label_propagation.cpp
    cpptoo: initial_partitioning.cpp
    cpptoo: initial_partitioner.cpp
```
I am compiling this library for OpenFOAM-plus. Also I found that kahip is compiled with scon but OpenFOAM-plus provide its own compile script, makeKAHIP. But, I am not sure if those scripts make difference cause I am not familiar with scon. FYI, I uploaded the building script.
[makeKAHIP.tar.gz](https://github.com/schulzchristian/KaHIP/files/1763984/makeKAHIP.tar.gz)
.

**Comment by schulzchristian** [comment]
can you try to clone the repository and run ./compile.sh? 
does that work for you?

**Comment by handrake0724** [comment]
I installed scons and tried compile.sh. It works. So, I guess the problem is in the building script, makeKAHIP.

**Comment by schulzchristian** [comment]
thanks! Can you help with this @olesenm?

**Comment by handrake0724** [comment]
Yes, sure. I made an issue on openfoam.com

**Comment by olesenm** [comment]
Issue resolved - https://develop.openfoam.com/Development/OpenFOAM-plus/issues/744

Newer gcc seems to require `-fpermissive` to compile using its own STL files.
