### ISSUE TITLE
A parallel partitioning API for external packages? 

### ISSUE THREAD

**Issue by fdkong** [schulzchristian/KaHIP#22]
We have went through the code of KaHIP, but KaHIP is still missing the parallel partitioning API for an external package such as PETSc, MOOSE or libMesh. It would be great if you guys could provide some APIs that are very similar to what ParMETIS has today.  

I emailed you guys a couple of months ago, and you guys claimed you would have something soon.

Could you guys let us what is the current status?

**Comment by schulzchristian** [comment]
Hey, I am working on a prototype. Will release probably next week.

Best
Christian

**Comment by fdkong** [comment]
> Hey, I am working on a prototype. Will release probably next week.
> 
> Best
> Christian

Thanks, @schulzchristian.

**Comment by schulzchristian** [comment]
Hi @fdkong,

I integrated a prototype. The interface is very similar to the parmetis interface. Please go ahead trying and let me know if that's usable for you. In the following days I will update the manual etc.

Best
Christian

**Comment by fdkong** [comment]
> Hi @fdkong,
> 
> I integrated a prototype. The interface is very similar to the parmetis interface. Please go ahead trying and let me know if that's usable for you. In the following days I will update the manual etc.
> 
> Best
> Christian

Sounds really cool.  I try it very soon.

One more question:  Do you support 64-bit integers as well? SO that we can solve a huge graph. I am asking because we are working large-scale simulations.

**Comment by schulzchristian** [comment]
Yes the interface supports this.

Best
Christian

**Comment by fdkong** [comment]
> Yes the interface supports this. Best Christian

Thanks.

**Comment by schulzchristian** [comment]
Hi @fdkong, did you have any chance to try?

**Comment by fdkong** [comment]
I’m still working on it. Will report back once have a good progress

**Comment by fdkong** [comment]
@schulzchristian The package works with clang or not? I manually replace  everything `CXX` and `CC` with `mpicxx` and `mpicc`. But still looks` g++` is involved. 

What is the reason you guys are using `scons` to compile the whole system?  Why require an `openmpi`? Should you respect a general MPI?


```
ld: warning: directory not found for option '-L/opt/local/lib'
ld: warning: directory not found for option '-L/opt/local/lib/openmpi'
ld: warning: directory not found for option '-L/usr/local/lib/openmpi'
scons: done building targets.
```

**Comment by fdkong** [comment]
@schulzchristian I actually got something:

```
[kongf][~/projects/petsc/src/mat/examples/tutorials]> mpirun -n 4  ./ex15  -mat_partitioning_type kahip 
log>=====================================
log>=============NEXT LEVEL==============
log>=====================================
log>cycle: 0 level: 0 parallel label compression took 0.00303507
log>cycle: 0 level: 0 contraction took 0.000952005
log>cycle: 0 level: 0 coarse nodes n=10, coarse edges m=18
log>=====================================
log>================ IP =================
log>=====================================
log>cycle: 0 total number of levels 1
log>cycle: 0 number of coarsest nodes 10
log>cycle: 0 number of coarsest edges 18
log>cycle: 0 coarsening took  0.00421095
rank 0 fingerprint 3 
partitioner call took 0.00482416rank 1 fingerprint 3 
rank 2 fingerprint 3 
rank 3 fingerprint 3 

log>cut computed by IP algorithm 3
log>balance computed by IP algorithm 1
log>cur edge cut 3
log>cur balance  1
log>cycle: 0 initial partitioning took 0.00507092
log>=====================================
log>============PREV LEVEL ==============
log>=====================================
log>cycle: 0 level: 0 projection took 8.70228e-05
log>cycle: 0 level: 0 label compression refinement took 1.09673e-05
log>cycle: 0 uncoarsening took 0.000139952
log>cycle: 0 k 4 cut 3 balance 1 time 0.00943184
IS Object: 4 MPI processes
  type: general
[0] Number of indices in set 3
[0] 0 3
[0] 1 3
[0] 2 3
[1] Number of indices in set 3
[1] 0 2
[1] 1 2
[1] 2 0
[2] Number of indices in set 2
[2] 0 0
[2] 1 1
[3] Number of indices in set 2
[3] 0 1
[3] 1 1

```

**Comment by schulzchristian** [comment]
cool, so it worked. Closing issue now.

Thanks for testing!
