### ISSUE TITLE
Fixed Size of The Set / Imbalance

### ISSUE THREAD

**Issue by myzinsky** [schulzchristian/KaHIP#3]
Hi,

I have a very simple example here:

I want to partition a graph in two sets. In total I have e.g. 2048 nodes, which should be partitioned in two sets (ε=0?). However, after the partitioning the sets are not balanced:

- Set1: 1023
- Set2: 1025

I need an exact half/half cut ... two sets with a fixed size.

As far as I understood from the documentation I have to use the KaBAPE for this kind of task:

```bash
mpirun -n 8 KaHIP/deploy/kaffpaE --k=2 --imbalance=0.0 --mh_enable_kabapE my.graph
```

Did I something wrong?

Best Regards

**Comment by schulzchristian** [comment]
please send me an email containing the graph.
Thanks!
