### ISSUE TITLE
Compiling KaHIP with Python3

### ISSUE THREAD

**Issue by IgorBaratta** [schulzchristian/KaHIP#32]
Typing `./compile.sh` in newer Ubuntu versions (18.04 or 18.10) gives:

```
/usr/bin/env: 'python': No such file or directory
compile error in node_separator. exiting.
```
Python3 is now the default in newer Ubuntu/Debian distros. Any plans on going in this direction?

....
Although running `compile_withcmake.sh` seems to work fine.

**Comment by schulzchristian** [comment]
Hi Igor,

thanks you for you message. I don't think this is specifically related to the KaHIP package, but scons. 
Can you compile anything else using your scons configruation/installation? 
On my machine, I have python3 and 2.7 both installed and this works perfectly fine.

Best
Christian

**Comment by schulzchristian** [comment]
also there is the possibility to use python3 [1].

Best
Christian

[1] https://stackoverflow.com/questions/48185262/how-to-execute-scons-in-a-python3-environment

**Comment by IgorBaratta** [comment]
Great. Thanks, now it's working fine  (with `#! /usr/bin/env python3`).
The only thing is that `print` in `SConstruct` is invoked without parentheses (mandatory in python3), but it's an easy fix here.

**Comment by schulzchristian** [comment]
perfect! If you have time to do so, could you issue a pull request?
I am closing the issue now.

Thanks!
Christian
