### ISSUE TITLE
Proposal: Make OpenMP an optional dependency

### ISSUE THREAD

**Issue by IgorBaratta** [schulzchristian/KaHIP#38]
Is it possible (desirable) to make OpenMP an optional dependency?
As far as I understand, OpenMP is only directly used in `kway_graph_refinement_commons.cpp` with the directive `critical` (one thread at a time). 

In my fork, I have defined a  preprocessor macro `USE_OPENMP`, which is set only in the case I would use OpenMP, and wraps the OpenMP calls.

What are the expected effects?

**Comment by schulzchristian** [comment]
Hi Igor, I will soon have a closer look.

**Comment by schulzchristian** [comment]
pull request #42 fixes this.
Thanks Igor!
