### ISSUE TITLE
Installation problems on Ubuntu

### ISSUE THREAD

**Issue by jaravad** [schulzchristian/KaHIP#43]
Hi, I was trying to run KaHIP on my Ubuntu machine, but after installing scons, openmpi and argtable, I'm getting an error at the time of running compile.sh. I have g++ 7.5.0 installed. Do I need to install specific versions of these packages?. I have installed the versions mentioned in the manual. When I run compile.sh the terminal shows a lot of lines. These are the last lines I get :

```
nmpi lib/algorithms/strongly_connected_components.cpp
scons: *** [optimized/lib/data_structure/graph_hierarchy.o] Error 127
mpicxx: error while loading shared libraries: libopen-pal.so.0: cannot open shared object file: No such file or directory
scons: *** [optimized/lib/algorithms/strongly_connected_components.o] Error 127
scons: building terminated because of errors.
compile error in kaffpaE. exiting.
```

**Comment by schulzchristian** [comment]
Could you try to compile it with cmake?
Just run ./compile_withcmake.sh.

Best
Christian

**Comment by jaravad** [comment]
Thanks a lot Christian, it worked using what you suggested
