### ISSUE TITLE
Support multi-dimensional vertex weights (multi-constraint partitioning algorithm)

### ISSUE THREAD

**Issue by hnsl** [schulzchristian/KaHIP#7]
This is currently supported by Metis.

Due to this, the statement "The graph format used by our partitioning programs is the same as used by Metis" in the documentation is currently false.

**Comment by schulzchristian** [comment]
Thank you for you comment. Can you point me to the place where Metis its multi-constraint part of the graph format is described?

Thanks
Christian

**Comment by hnsl** [comment]
http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/manual.pdf

4.1.1 Graph file

KaHIP would have been nice to use because of the mapping/QAP feature, but since it's lacking this important feature (for me) I have to stick with Metis. Thanks!

**Comment by schulzchristian** [comment]
Thanks for the link! We will fix our manual soon. 

Regarding multi-contraint partitioning -- we have this on our TODO list, but currently it does not have high priority. 

Regarding mapping -- the full mapping functionality is also available in VieQAP [1], so I recommend multi-contraint partitioning your instances first and then use the mapping algorithms in VieQAP to map or solve a QAP. 

Best
Christian 

[1] http://viem.taa.univie.ac.at/
