### ISSUE TITLE
parhip on cluster for parallel graph partitioning

### ISSUE THREAD

**Issue by monicasenapati** [schulzchristian/KaHIP#8]
I have installed all the prerequisites: Scons, argtable and openmpi. 
Now, I am able to run a simple MPI hello world program which communicates between it's other nodes. However when I run the parhip program as _"senapati@ctl:~/KaHIP/deploy$  mpirun -n 2 -host cp-1,cp-2 parhip ../examples/delaunay_n15.graph --k=3 --preconfiguration=ecosocial"_
(cp-1 and cp-2 are other nodes in the cluster), the following error occurs:

_[cp-1:16051] *** An error occurred in MPI_Allreduce: the reduction operation MPI_SUM is not defined on the MPI_INTEGER datatype
[cp-1:16051] *** reported by process [2107572225,545460846592]
[cp-1:16051] *** on communicator MPI_COMM_WORLD
[cp-1:16051] *** MPI_ERR_OP: invalid reduce operation
[cp-1:16051] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[cp-1:16051] ***    and potentially your MPI job)
[ctl.<hostname>:15579] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[ctl.<hostname>:15579] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages_

Please let me know how this issue can be resolved or why is this occurring.

**Comment by schulzchristian** [comment]
Hi Monica,

it looks like you openmpi is not working correctly. Have you been able to run any other non-trivial code on that installation?

Best,
Christian

**Comment by monicasenapati** [comment]
Yes I tried a simple hello program present in the examples folder of open mpi and it worked fine.

Thanks & regards,
Monica

On Sep 16, 2017, at 6:37 AM, Christian Schulz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Monica,

it looks like you openmpi is not working correctly. Have you been able to run any other non-trivial code on that installation?

Best,
Christian

**Comment by schulzchristian** [comment]
We now fixed the bug. Closing the issue.
